server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Hashli fayllar uzoq keshlanadi.
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # SPA — barcha yo'llar index.html ga tushadi (React Router hal qiladi).
    location / {
        try_files $uri $uri/ /index.html;
    }
}
